version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - run:
          name: Install Newman
          command: sudo npm install -g newman
      - run:
          name: Run Postman Tests
          command: |
            newman run Lists.postman_collection.json \
              --environment Production.postman_environment.json \
              --reporters cli,json,html \
              --reporter-html-export newman/report.html
      - store_artifacts:
          path: newman/report.html
          destination: postman-report

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
